name: Deploy to FTP Server for Production

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Upload to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password:  ${{ secrets.FTP_PASSWORD }}
        local-dir: './'
        server-dir: ${{ vars.FTP_PROD_DIRECTORY }}
        protocol: ${{ vars.FTP_PROTOCOL }}
        port: ${{ vars.FTP_PORT }}
        dangerous-clean-slate: true
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.trash/**
          **/.vscode/**
          README.md
